"""Filesystem I/O for memory entries.

One file per entry: <tier_root>/<name>.md. Frontmatter is a strict subset
of YAML (flat key:value, plus `|` block scalars), reused from the same
parser shape skills/io.py uses.

A derived index file MEMORY.md lives in each tier root. It is rebuilt by
rebuild_index() after any write/delete; it is never authored by hand.
"""
from __future__ import annotations

from pathlib import Path

from .errors import MemoryWriteError
from .models import Memory, Scope

MEMORY_INDEX_FILENAME = "MEMORY.md"

_REQUIRED_FIELDS = ("description", "type", "created_at", "updated_at", "source_session")


def parse_memory_md(
    text: str, *, filename_stem: str, source_path: Path, scope: Scope,
) -> Memory | str:
    """Return Memory on success, or short error string on failure."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return "no frontmatter"

    fm: dict[str, str] = {}
    end_idx: int | None = None
    i = 1
    while i < len(lines):
        raw = lines[i]
        if raw.strip() == "---":
            end_idx = i
            break
        if ":" not in raw:
            i += 1
            continue
        key, _, val = raw.partition(":")
        key, val = key.strip(), val.strip()
        if val in ("|", ">"):
            collected: list[str] = []
            j = i + 1
            while j < len(lines):
                nxt = lines[j]
                if nxt.strip() == "---":
                    break
                if nxt and not nxt[0].isspace():
                    break
                collected.append(nxt.strip())
                j += 1
            fm[key] = " ".join(c for c in collected if c)
            i = j
            continue
        fm[key] = val
        i += 1

    if end_idx is None:
        return "unclosed frontmatter"

    for k in _REQUIRED_FIELDS:
        if not fm.get(k, "").strip():
            return f"missing {k}"

    name_field = fm.get("name", "").strip()
    if name_field and name_field != filename_stem:
        return "name mismatch"

    body = "\n".join(lines[end_idx + 1:]).strip()
    if not body:
        return "empty body"

    return Memory(
        name=filename_stem,
        description=fm["description"],
        type=fm["type"],
        body=body,
        created_at=fm["created_at"],
        updated_at=fm["updated_at"],
        source_session=fm["source_session"],
        scope=scope,
        source_path=source_path,
    )


def serialize_memory(m: Memory) -> str:
    return (
        "---\n"
        f"name: {m.name}\n"
        f"description: {m.description}\n"
        f"type: {m.type}\n"
        f"created_at: {m.created_at}\n"
        f"updated_at: {m.updated_at}\n"
        f"source_session: {m.source_session}\n"
        "---\n"
        "\n"
        f"{m.body.rstrip()}\n"
    )


def write_memory(m: Memory, *, tier_root: Path) -> Path:
    tier_root.mkdir(parents=True, exist_ok=True)
    path = tier_root / f"{m.name}.md"
    try:
        path.write_text(serialize_memory(m), encoding="utf-8")
    except OSError as e:
        raise MemoryWriteError(f"could not write {path}: {e}") from e
    try:
        path.chmod(0o600)
    except OSError:
        pass
    return path


def delete_memory(name: str, *, tier_root: Path) -> bool:
    path = tier_root / f"{name}.md"
    if not path.exists():
        return False
    path.unlink()
    return True


def rebuild_index(*, tier_root: Path) -> Path:
    """Scan tier_root for *.md (except MEMORY.md) and write MEMORY.md."""
    tier_root.mkdir(parents=True, exist_ok=True)
    bullets: list[str] = []
    for child in sorted(tier_root.iterdir()):
        if not child.is_file() or child.name == MEMORY_INDEX_FILENAME:
            continue
        if child.suffix != ".md":
            continue
        try:
            text = child.read_text(encoding="utf-8")
        except OSError:
            continue
        parsed = parse_memory_md(
            text, filename_stem=child.stem, source_path=child, scope="global",
        )
        if isinstance(parsed, str):
            continue
        bullets.append(f"- **{parsed.name}** — {parsed.description}")

    header = (
        "<!-- Auto-generated by codey. Do not edit by hand; edit "
        "individual entry files. -->\n"
        "# Memory\n\n"
    )
    body = "\n".join(bullets) + ("\n" if bullets else "")
    path = tier_root / MEMORY_INDEX_FILENAME
    path.write_text(header + body, encoding="utf-8")
    try:
        path.chmod(0o600)
    except OSError:
        pass
    return path
